Repository lord-server/lord, pull requests merged in 2018-12, with the labels that each got.

#92 Kittens
  mods/lottmobs/animals.lua
  mods/lottmobs/eggs.lua
  mods/lottmobs/models/mobs_kitten.b3d
  mods/lottmobs/models/mobs_rat.b3d
  mods/lottmobs/sounds/mobs_kitten.ogg
  mods/lottmobs/spawn.lua
  mods/lottmobs/textures/mobs_hairball.png
  mods/lottmobs/textures/mobs_kitten_ginger.png
  mods/lottmobs/textures/mobs_kitten_inv.png
  mods/lottmobs/textures/mobs_kitten_sandy.png
  mods/lottmobs/textures/mobs_kitten_splotchy.png
  mods/lottmobs/textures/mobs_kitten_striped.png
  mods/lottmobs/textures/rat.png
  mods/mobs/api.lua
Labels: enhancement, internal, mod, waiting on review

#135 Fix tame messages by removing them
  mods/mobs/api.lua
  mods/mobs/locale/ru.txt
Labels: waiting on review

#139 Increase egg mass
  mods/lottmobs/animals.lua
Labels: enhancement

#140 Fix kittents
  mods/lottmobs/animals.lua
Labels: bug

#138 Исправления топоров
  mods/arrows/axe.lua
  mods/arrows/locale/en.txt
  mods/arrows/locale/ru.txt
  mods/lottthrowing/locale/en.txt
  mods/lottthrowing/locale/ru.txt
Labels: bug

#136 локализация стрел
  mods/arrows/locale/en.txt
  mods/arrows/locale/ru.txt
  mods/lottthrowing/locale/en.txt
  mods/lottthrowing/locale/ru.txt
Labels: localization

#134 Поменял текстуры топоров, Удалил закоментированый код.
  mods/lottores/init.lua
  mods/lottores/textures/lottores_copperaxe.png
  mods/lottores/textures/lottores_galvornaxe.png
  mods/lottores/textures/lottores_goldaxe.png
  mods/lottores/textures/lottores_mithrilaxe.png
  mods/lottores/textures/lottores_silveraxe.png
  mods/lottores/textures/lottores_tinaxe.png
  mods/tools/textures/tools_axe_bronze.png
  mods/tools/textures/tools_axe_copper.png
  mods/tools/textures/tools_axe_galvorn.png
  mods/tools/textures/tools_axe_gold.png
  mods/tools/textures/tools_axe_mithril.png
  mods/tools/textures/tools_axe_silver.png
  mods/tools/textures/tools_axe_steel.png
  mods/tools/textures/tools_axe_stone.png
  mods/tools/textures/tools_axe_tin.png
  mods/tools/textures/tools_axe_wood.png
  mods/tools/textures/tools_battleaxe_bronze.png
  mods/tools/textures/tools_battleaxe_copper.png
  mods/tools/textures/tools_battleaxe_galvorn.png
  mods/tools/textures/tools_battleaxe_gold.png
  mods/tools/textures/tools_battleaxe_mithril.png
  mods/tools/textures/tools_battleaxe_silver.png
  mods/tools/textures/tools_battleaxe_steel.png
  mods/tools/textures/tools_battleaxe_stone.png
  mods/tools/textures/tools_battleaxe_tin.png
  mods/tools/textures/tools_battleaxe_wood.png
Labels: enhancement, graphics, waiting on review
