Repository lord-server/lord, pull requests merged in 2019-05, with the labels that each got.

#226 Fix health display for mobs
  mods/mobs/api.lua
Labels: enhancement, needs testing

#225 Kill mobs with health < 0
  mods/mobs/api.lua
Labels: fix, needs testing

#227 Fix rebase problem and handle case of old mobs, who don't have original health
  mods/mobs/api.lua
Labels: fix

#229 Изменение модели игрока
  mods/lottarmor/models/lottarmor_character.b3d
  mods/lottarmor/models/lottarmor_character.blend
  mods/lottarmor/models/lottarmor_character_old.b3d
  mods/lottarmor/models/lottarmor_character_old.blend
Labels: move-to-5.0, needs testing
