Repository lord-server/lord, pull requests merged in 2019-03, with the labels that each got.

#206 Fix ghost nodes registration. fix #192
  mods/defaults/init.lua
  mods/lordlib/init.lua
Labels: fix, needs testing

#207 Decrease bolt mass
  mods/arrows/arrows.lua
Labels: fix, internal, mod, needs testing

#221 Fixes #220. Fix jump through Palatir
  mods/lord_classes/init.lua
Labels: fix
