Repository lord-server/lord, pull requests merged in 2019-01, with the labels that each got.

#144 Функции звуков гравия и металла (fixes #110)
  mods/default/functions.lua
  mods/default/nodes.lua
  mods/default/sounds/default_dig_metal.ogg
  mods/default/sounds/default_dug_metal.1.ogg
  mods/default/sounds/default_dug_metal.2.ogg
  mods/default/sounds/default_metal_footstep.1.ogg
  mods/default/sounds/default_metal_footstep.2.ogg
  mods/default/sounds/default_metal_footstep.3.ogg
  mods/default/sounds/default_place_node_metal.1.ogg
  mods/default/sounds/default_place_node_metal.2.ogg
  mods/lord_homedecor/building_blocks.lua
  mods/lottores/init.lua
  mods/nomedia.txt
  mods/vessels/init.lua
Labels: enhancement, sound

#151 replace `lord_homedecor.gettext` with `lord.require_intllib()`
  mods/lord_homedecor/crafts.lua
  mods/lord_homedecor/furniture_medieval.lua
  mods/lord_homedecor/handlers/inventory.lua
  mods/lord_homedecor/init.lua
  mods/lord_homedecor/lighting.lua
  mods/lord_homedecor/misc-nodes.lua
  mods/lord_homedecor/roofing.lua
  mods/lord_homedecor/shutters.lua
  mods/lord_homedecor/window_treatments.lua
Labels: enhancement, refactoring

#126 Grinder refactoring
  mods/grinder/init.lua
  mods/grinder/src/grinder.lua
  mods/grinder/src/grinder/Grinder.lua
  mods/grinder/src/grinder/Processor.lua
  mods/grinder/src/grinder/Recipe.lua
  mods/grinder/src/grinder/definition/craft.lua
  mods/grinder/src/grinder/definition/node.lua
  mods/grinder/src/grinder/definition/node/active.lua
  mods/grinder/src/grinder/definition/node/form.lua
  mods/grinder/src/grinder/definition/node/inactive.lua
  mods/grinder/src/grinder/definition/recipes.lua
Labels: internal, mod, refactoring, waiting on review

#155 Fix tree instalation on pedestal
  mods/lottplants/nodes.lua
Labels: bug

#153 fix fuel burning after grinder overflow
  mods/grinder/src/grinder/Grinder.lua
  mods/grinder/src/grinder/Processor.lua
  mods/grinder/src/grinder/Recipe.lua
Labels: bug

#171 Fix attack code
  mods/mobs/api.lua
Labels: fix
