Repository lord-server/lord, pull requests merged in 2021-12, with the labels that each got.

#429 WIP: Обнов. MTG/beds. Fix #312 Сброс скорости после сна
  mods/_minetest_game/beds/README.txt
  mods/_minetest_game/beds/api.lua
  mods/_minetest_game/beds/beds.lua
  mods/_minetest_game/beds/depends.txt
  mods/_minetest_game/beds/functions.lua
  mods/_minetest_game/beds/init.lua
  mods/_minetest_game/beds/license.txt
  mods/_minetest_game/beds/locale/beds.de.tr
  mods/_minetest_game/beds/locale/beds.eo.tr
  mods/_minetest_game/beds/locale/beds.es.tr
  mods/_minetest_game/beds/locale/beds.fr.tr
  mods/_minetest_game/beds/locale/beds.id.tr
  mods/_minetest_game/beds/locale/beds.it.tr
  mods/_minetest_game/beds/locale/beds.jbo.tr
  mods/_minetest_game/beds/locale/beds.ms.tr
  mods/_minetest_game/beds/locale/beds.pt_BR.tr
  mods/_minetest_game/beds/locale/beds.ru.tr
  mods/_minetest_game/beds/locale/beds.se.tr
  mods/_minetest_game/beds/locale/beds.sk.tr
  mods/_minetest_game/beds/locale/beds.zh_CN.tr
  mods/_minetest_game/beds/locale/beds.zh_TW.tr
  mods/_minetest_game/beds/locale/en.txt
  mods/_minetest_game/beds/locale/ru.txt
  mods/_minetest_game/beds/locale/template.txt
  mods/_minetest_game/beds/mod.conf
  mods/_minetest_game/beds/spawns.lua
  mods/_minetest_game/beds/textures/beds_bed.png
  mods/_minetest_game/beds/textures/beds_bed_fancy.png
  mods/_minetest_game/beds/textures/beds_bed_foot.png
  mods/_minetest_game/beds/textures/beds_bed_head.png
  mods/_minetest_game/beds/textures/beds_bed_side1.png
  mods/_minetest_game/beds/textures/beds_bed_side2.png
  mods/_minetest_game/beds/textures/beds_bed_side_bottom.png
  mods/_minetest_game/beds/textures/beds_bed_side_bottom_r.png
  mods/_minetest_game/beds/textures/beds_bed_side_top.png
  mods/_minetest_game/beds/textures/beds_bed_side_top_r.png
  mods/_minetest_game/beds/textures/beds_bed_top1.png
  mods/_minetest_game/beds/textures/beds_bed_top2.png
  mods/_minetest_game/beds/textures/beds_bed_top_bottom.png
  mods/_minetest_game/beds/textures/beds_bed_top_top.png
  mods/_minetest_game/beds/textures/beds_bed_under.png
  mods/_minetest_game/beds/textures/beds_transparent.png
Labels: waiting on author, fix, MTG, waiting-5.3

#496 Disable string patterns in craft books
  mods/_lott/lottinventory/zcg.lua
Labels: fix

#502 Replace nonexistent beds with beds:bed
  mods/_lott/lottmapgen/chests.lua
  mods/_lott/lottmapgen/schems/gondorfort.we
  mods/_lott/lottmapgen/schems/hobbithole.we
Labels: fix

#494 Ingot textures fix 3
  mods/_minetest_game/default/textures/default_bronze_ingot.png
  mods/_minetest_game/default/textures/default_copper_ingot.png
  mods/_minetest_game/default/textures/default_gold_ingot.png
  mods/_minetest_game/default/textures/default_steel_ingot.png
  mods/lord/_overwrites/MTG/default/textures/default_bronze_ingot.png
  mods/lord/_overwrites/MTG/default/textures/default_copper_ingot.png
  mods/lord/_overwrites/MTG/default/textures/default_gold_ingot.png
  mods/lord/_overwrites/MTG/default/textures/default_steel_ingot.png
Labels: fix

#506 Update MTG/vessels
  mods/_minetest_game/vessels/README.txt
  mods/_minetest_game/vessels/depends.txt
  mods/_minetest_game/vessels/init.lua
  mods/_minetest_game/vessels/license.txt
  mods/_minetest_game/vessels/locale/en.txt
  mods/_minetest_game/vessels/locale/ru.txt
  mods/_minetest_game/vessels/locale/template.txt
  mods/_minetest_game/vessels/locale/vessels.de.tr
  mods/_minetest_game/vessels/locale/vessels.es.tr
  mods/_minetest_game/vessels/locale/vessels.fr.tr
  mods/_minetest_game/vessels/locale/vessels.id.tr
  mods/_minetest_game/vessels/locale/vessels.it.tr
  mods/_minetest_game/vessels/locale/vessels.jbo.tr
  mods/_minetest_game/vessels/locale/vessels.ms.tr
  mods/_minetest_game/vessels/locale/vessels.pt_BR.tr
  mods/_minetest_game/vessels/locale/vessels.ru.tr
  mods/_minetest_game/vessels/locale/vessels.se.tr
  mods/_minetest_game/vessels/locale/vessels.sk.tr
  mods/_minetest_game/vessels/locale/vessels.zh_CN.tr
  mods/_minetest_game/vessels/locale/vessels.zh_TW.tr
  mods/_minetest_game/vessels/mod.conf
  mods/_minetest_game/vessels/textures/vessels_drinking_glass.png
  mods/_minetest_game/vessels/textures/vessels_drinking_glass_inv.png
  mods/_minetest_game/vessels/textures/vessels_glass_bottle.png
  mods/_minetest_game/vessels/textures/vessels_glass_fragments.png
  mods/_minetest_game/vessels/textures/vessels_shelf.png
  mods/_minetest_game/vessels/textures/vessels_shelf_slot.png
  mods/_minetest_game/vessels/textures/vessels_steel_bottle.png
  mods/lord/_overwrites/MTG/vessels/init.lua
  mods/lord/_overwrites/MTG/vessels/mod.conf
  mods/lord/_overwrites/MTG/vessels/readme.md
  mods/lord/_overwrites/MTG/vessels/textures/vessels_drinking_glass.png
  mods/lord/_overwrites/MTG/vessels/textures/vessels_drinking_glass_inv.png
  mods/lord/_overwrites/MTG/vessels/textures/vessels_glass_bottle.png
  mods/lord/_overwrites/MTG/vessels/textures/vessels_glass_bottle_inv.png
  mods/lord/_overwrites/MTG/vessels/textures/vessels_glass_fragments.png
  mods/lord/_overwrites/MTG/vessels/textures/vessels_steel_bottle.png
  mods/lord/_overwrites/MTG/vessels/textures/vessels_steel_bottle_inv.png
  mods/lord/_overwrites/readme.md
Labels: mod, external, update, MTG

#507 Update mods: MTG/dye
  mods/_minetest_game/dye/README.txt
  mods/_minetest_game/dye/depends.txt
  mods/_minetest_game/dye/init.lua
  mods/_minetest_game/dye/license.txt
  mods/_minetest_game/dye/locale/dye.de.tr
  mods/_minetest_game/dye/locale/dye.es.tr
  mods/_minetest_game/dye/locale/dye.fr.tr
  mods/_minetest_game/dye/locale/dye.id.tr
  mods/_minetest_game/dye/locale/dye.it.tr
  mods/_minetest_game/dye/locale/dye.jbo.tr
  mods/_minetest_game/dye/locale/dye.ms.tr
  mods/_minetest_game/dye/locale/dye.pt_BR.tr
  mods/_minetest_game/dye/locale/dye.ru.tr
  mods/_minetest_game/dye/locale/dye.se.tr
  mods/_minetest_game/dye/locale/dye.sk.tr
  mods/_minetest_game/dye/locale/dye.zh_CN.tr
  mods/_minetest_game/dye/locale/dye.zh_TW.tr
  mods/_minetest_game/dye/locale/en.txt
  mods/_minetest_game/dye/locale/ru.txt
  mods/_minetest_game/dye/locale/template.txt
  mods/_minetest_game/dye/mod.conf
  mods/_minetest_game/dye/textures/dye_black.png
  mods/_minetest_game/dye/textures/dye_blue.png
  mods/_minetest_game/dye/textures/dye_brown.png
  mods/_minetest_game/dye/textures/dye_cyan.png
  mods/_minetest_game/dye/textures/dye_dark_green.png
  mods/_minetest_game/dye/textures/dye_dark_grey.png
  mods/_minetest_game/dye/textures/dye_green.png
  mods/_minetest_game/dye/textures/dye_grey.png
  mods/_minetest_game/dye/textures/dye_magenta.png
  mods/_minetest_game/dye/textures/dye_orange.png
  mods/_minetest_game/dye/textures/dye_pink.png
  mods/_minetest_game/dye/textures/dye_red.png
  mods/_minetest_game/dye/textures/dye_violet.png
  mods/_minetest_game/dye/textures/dye_white.png
  mods/_minetest_game/dye/textures/dye_yellow.png
  mods/lord/_overwrites/MTG/dye/init.lua
  mods/lord/_overwrites/MTG/dye/mod.conf
  mods/lord/_overwrites/MTG/dye/readme.md
  mods/lord/_overwrites/MTG/dye/textures/dye_black.png
  mods/lord/_overwrites/MTG/dye/textures/dye_blue.png
  mods/lord/_overwrites/MTG/dye/textures/dye_brown.png
  mods/lord/_overwrites/MTG/dye/textures/dye_cyan.png
  mods/lord/_overwrites/MTG/dye/textures/dye_dark_green.png
  mods/lord/_overwrites/MTG/dye/textures/dye_dark_grey.png
  mods/lord/_overwrites/MTG/dye/textures/dye_green.png
  mods/lord/_overwrites/MTG/dye/textures/dye_grey.png
  mods/lord/_overwrites/MTG/dye/textures/dye_magenta.png
  mods/lord/_overwrites/MTG/dye/textures/dye_orange.png
  mods/lord/_overwrites/MTG/dye/textures/dye_pink.png
  mods/lord/_overwrites/MTG/dye/textures/dye_red.png
  mods/lord/_overwrites/MTG/dye/textures/dye_violet.png
  mods/lord/_overwrites/MTG/dye/textures/dye_white.png
  mods/lord/_overwrites/MTG/dye/textures/dye_yellow.png
Labels: mod, external, update, MTG
