Repository lord-server/lord, pull requests merged in 2021-06, with the labels that each got.

#365 lord/*/depends.txt -> mod.conf
  mods/lord/arrows/depends.txt
  mods/lord/arrows/mod.conf
  mods/lord/death_handler/depends.txt
  mods/lord/death_handler/mod.conf
  mods/lord/defaults/depends.txt
  mods/lord/defaults/mod.conf
  mods/lord/embrasure/depends.txt
  mods/lord/embrasure/mod.conf
  mods/lord/grinder/depends.txt
  mods/lord/grinder/mod.conf
  mods/lord/legacy/depends.txt
  mods/lord/legacy/mod.conf
  mods/lord/lord_base_commands/depends.txt
  mods/lord/lord_base_commands/mod.conf
  mods/lord/lord_base_privs/depends.txt
  mods/lord/lord_base_privs/mod.conf
  mods/lord/lord_classes/depends.txt
  mods/lord/lord_classes/mod.conf
  mods/lord/lord_doors/depends.txt
  mods/lord/lord_doors/mod.conf
  mods/lord/lord_homedecor/depends.txt
  mods/lord/lord_homedecor/mod.conf
  mods/lord/lord_info/depends.txt
  mods/lord/lord_info/mod.conf
  mods/lord/lord_mail/depends.txt
  mods/lord/lord_mail/mod.conf
  mods/lord/lord_money/depends.txt
  mods/lord/lord_money/mod.conf
  mods/lord/lord_names_rules/depends.txt
  mods/lord/lord_names_rules/mod.conf
  mods/lord/lordlib/depends.txt
  mods/lord/lordlib/mod.conf
  mods/lord/lottarmor/depends.txt
  mods/lord/lottarmor/mod.conf
  mods/lord/mega_sl/depends.txt
  mods/lord/mega_sl/mod.conf
  mods/lord/npc/depends.txt
  mods/lord/player/depends.txt
  mods/lord/player/mod.conf
  mods/lord/tools/depends.txt
  mods/lord/tools/mod.conf
Labels: refactoring

#371 Dice bugfix
  mods/lord/dice/init.lua
Labels: fix

#368 Periodic damage hobbits in certain area
  mods/lord/lord_classes/effects.lua
  mods/lord/lord_classes/init.lua
Labels: feature, implementation, lord
