Repository lord-server/lord, pull requests merged in 2021-09, with the labels that each got.

#398 Fix get skin for shadow
  mods/lord/lord_classes/generate_face_prewiew.sh
  mods/lord/lord_classes/init.lua
Labels: fix

#408 Ingot textures
  mods/_lott/lottores/textures/lottores_galvorn_ingot.png
  mods/_lott/lottores/textures/lottores_lead_ingot.png
  mods/_lott/lottores/textures/lottores_mithril_ingot.png
  mods/_lott/lottores/textures/lottores_silver_ingot.png
  mods/_lott/lottores/textures/lottores_tilkal_ingot.png
  mods/_lott/lottores/textures/lottores_tin_ingot.png
  mods/_lott/lottother/textures/lottother_ringsilver_ingot.png
  mods/_minetest_game/default/textures/default_bronze_ingot.png
  mods/_minetest_game/default/textures/default_copper_ingot.png
  mods/_minetest_game/default/textures/default_gold_ingot.png
  mods/_minetest_game/default/textures/default_steel_ingot.png
Labels: graphics

#396 Улучшение горного посоха
  mods/lord/mountgen/cone.lua
  mods/lord/mountgen/diamond_square.lua
  mods/lord/mountgen/height_map.lua
  mods/lord/mountgen/init.lua
  mods/lord/mountgen/map.lua
  mods/lord/mountgen/mountgen.lua
Labels: enhancement

#415 Added single dot and one sided dwarfstones
  mods/_lott/lottblocks/textures/lottblocks_dwarfstone_stripe_bottom.png
  mods/_lott/lottblocks/textures/lottblocks_dwarfstone_stripe_r.png
  mods/_lott/lottblocks/textures/lottblocks_dwarfstone_stripe_top.png
  mods/lord/lord_blocks/init.lua
  mods/lord/lord_blocks/locale/default.ru.tr
  mods/lord/lord_blocks/locale/lord_blocks.en.tr
  mods/lord/lord_blocks/locale/lord_blocks.ru.tr
  mods/lord/lord_blocks/mod.conf
  mods/lord/lord_blocks/textures/lottblocks_dwarfstone_stripe_double.png
  mods/lord/lord_blocks/textures/lottblocks_dwarfstone_stripe_onesided_bottom.png
  mods/lord/lord_blocks/textures/lottblocks_dwarfstone_stripe_onesided_top.png
  mods/lord/lord_blocks/textures/lottblocks_dwarfstone_stripe_singledot_bottom.png
  mods/lord/lord_blocks/textures/lottblocks_dwarfstone_stripe_singledot_top.png
Labels: enhancement, implementation

#420 Fix crash on /info
  mods/lord/lord_spawn/init.lua
Labels: fix

#421 Admin store fix
  mods/lord/lord_money/locale/lord_money.en.tr
  mods/lord/lord_money/locale/lord_money.ru.tr
  mods/lord/lord_money/shop.lua
Labels: fix

#424 Ускорение работы горного посоха
  mods/lord/mountgen/map.lua
  mods/lord/mountgen/mountgen.lua
Labels: enhancement, performance

#427 fixes #418. Fix search in craft books after MT translate system applied
  mods/_lott/lottinventory/master.lua
  mods/_lott/lottinventory/zcg.lua
  mods/_various/intllib/init.lua
Labels: fix

#434 Boat alias hotfix
  mods/lord/_overwrites/MTG/boats/init.lua
Labels: fix, MTG

#436 Check for nil when flame nodes
  mods/lord/arrows/magic.lua
Labels: fix

#443 Исправление бага с менялой
  mods/lord/npc/changer_mob.lua
Labels: fix, mobs

#445 Add missing is_creative_enabled function
  mods/lord/lordlib/init.lua
Labels: mod, fix, MTG
