Repository lord-server/lord, pull requests merged in 2022-11, with the labels that each got.

#808 Fixed alpha in gondor door texture
  mods/lord/lord_doors/textures/lord_doors_gondor.png
Labels: lord, graphics, fix

#810 Новая текстура пшеницы
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_1.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_2.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_3.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_4.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_5.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_6.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_7.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_8.png
  mods/lord/_overwrites/MTG/farming/textures/farming_wheat_seed.png
Labels: graphics

#811 Новая текстура хлопка
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_1.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_2.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_3.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_4.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_5.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_6.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_7.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_8.png
  mods/lord/_overwrites/MTG/farming/textures/farming_cotton_seed.png
Labels: graphics

#812 Новая текстура ягод
  mods/_lott/lottfarming/textures/lottfarming_berries.png
  mods/_lott/lottfarming/textures/lottfarming_berries_1.png
  mods/_lott/lottfarming/textures/lottfarming_berries_2.png
  mods/_lott/lottfarming/textures/lottfarming_berries_3.png
  mods/_lott/lottfarming/textures/lottfarming_berries_4.png
  mods/_lott/lottfarming/textures/lottfarming_berries_seed.png
  mods/_lott/lottplants/textures/lottplants_berries_wild.png
Labels: graphics

#815 782-fix
  mods/lord/_overwrites/MTG/carts/crafting.lua
Labels: fix, MTG

#819 replace deprecated calls with new ones
  mods/_lott/lottblocks/palantiri.lua
  mods/_lott/lottmobs/animals.lua
  mods/_lott/lottmobs/horse.lua
  mods/_lott/lottother/init.lua
  mods/_minetest_game/default/mapgen.lua
  mods/_various/icicles/init.lua
  mods/_various/mobs/api.lua
  mods/_various/mobs_fish/init.lua
  mods/_various/painting/init.lua
  mods/lord/arena/init.lua
  mods/lord/lord_spawn/init.lua
  mods/lord/lottarmor/armor.lua
  mods/lord/mypos/init.lua
Labels: refactoring

#820 fix books capabilities for correct tooltips. fixes #800
  mods/_lott/lottinventory/brewing.lua
  mods/_lott/lottinventory/cooking.lua
  mods/_lott/lottinventory/forbidden.lua
  mods/_lott/lottinventory/master.lua
  mods/_lott/lottinventory/potions.lua
  mods/_lott/lottinventory/protection.lua
  mods/_lott/lottinventory/zcg.lua
Labels: fix

#821 fix quit from protector form by `escape`. fixes #524
  mods/_various/protector_lott/init.lua
Labels: fix

#818 Новые текстуры для HUD'а
  mods/_various/hud_modpack/hbarmor/textures/hbarmor_bgicon.png
  mods/_various/hud_modpack/hbarmor/textures/hbarmor_icon.png
  mods/_various/hud_modpack/hbhunger/textures/hbhunger_bgicon.png
  mods/_various/hud_modpack/hbhunger/textures/hbhunger_icon.png
  mods/_various/hud_modpack/hbhunger/textures/hbhunger_icon_health_poison.png
  mods/_various/hud_modpack/hbhunger/textures/hbhunger_icon_health_regen.png
  mods/_various/hud_modpack/hudbars/textures/hudbars_bgicon_breath.png
  mods/_various/hud_modpack/hudbars/textures/hudbars_bgicon_health.png
  mods/_various/hud_modpack/hudbars/textures/hudbars_icon_breath.png
  mods/_various/hud_modpack/hudbars/textures/hudbars_icon_health.png
Labels: graphics, hud

#825 fix ignition by a torch; add tooltip help. fixes #697, fixes #560
  mods/lord/lord_default/init.lua
  mods/lord/lord_default/locale/lord_default.en.tr
  mods/lord/lord_default/locale/lord_default.ru.tr
  mods/lord/lord_default/locale/template.txt
Labels: fix

#834 Replace deprecated `vel` and `acc` attributes in bees. Fixes #828
  mods/lord/bees/init.lua
Labels: lord, fix
