Repository lord-server/lord, pull requests merged in 2022-12, with the labels that each got.

#858 #268 #831 remove creative mod. Closes #831
  mods/_minetest_game/creative/depends.txt
  mods/_minetest_game/creative/init.lua
  mods/_minetest_game/creative/license.txt
  mods/_minetest_game/creative/locale/en.txt
  mods/_minetest_game/creative/locale/ru.txt
Labels: mod, MTG

#859 Remove `default.creative` & usages. Closes #857
  mods/_lott/lottblocks/misc.lua
  mods/_lott/lottblocks/wooden_stuff.lua
  mods/_lott/lottfarming/init.lua
  mods/_lott/lottfarming/pipeweed.lua
  mods/_lott/lottmobs/boar.lua
  mods/_lott/lottmobs/horse.lua
  mods/_lott/lottmobs/init.lua
  mods/_lott/lottmobs/warg.lua
  mods/_lott/lottother/flags.lua
  mods/_lott/lottthrowing/init.lua
  mods/_minetest_game/default/init.lua
  mods/_various/campfire/campfire.lua
  mods/_various/hud_modpack/hbsprint/init.lua
  mods/_various/mobs/api.lua
  mods/_various/signs_lib/init.lua
  mods/lord/arrows/init.lua
  mods/lord/bones/init.lua
  mods/lord/bones/skeleton.lua
  mods/lord/defaults/init.lua
  mods/lord/lord_homedecor/exterior.lua
  mods/lord/lord_homedecor/handlers/expansion.lua
  mods/lord/lord_homedecor/init.lua
  mods/lord/lordlib/init.lua
Labels: MTG

#860 #257 Update MTG/default: init.lua: move legacy `default.gui_*`. Closes #267
  mods/_minetest_game/default/init.lua
  mods/_minetest_game/readme.md
  mods/lord/legacy/init.lua
  mods/lord/legacy/mod.conf
Labels: MTG

#861 Fixes #853. Define use_texture_alpha for protector sign (set to clip)
  mods/_various/protector_lott/init.lua
Labels: needs review, fix, trivial

#870 Fixes #865. Slightly renew nickname filter algorithm
  mods/lord/lord_names_rules/init.lua
Labels: fix

#875 Fixes #873. Replace registered_player -> minetest.player_exists
  mods/lord/alarm/alarm1.lua
  mods/lord/alarm/init.lua
Labels: fix

#529 List arenas with health show in config
  .luacheckrc
  minetest.conf.prod
  minetest.conf.test
  mods/lord/player/arena_health.lua
  util/minetest_types.lua
Labels: enhancement

#876 Fixes 799. Check if item is registered, if it's not, return nil
  mods/_various/itemframes/init.lua
Labels: fix

#882 Remove mentions of not registered doors
  mods/_lott/lottmapgen/schems/hobbithole.we
  mods/_lott/lottmapgen/schems/mirkhouse.we
Labels: fix

#883 Fixes #878. Add 'itemframes' mod as a dependency for 'defaults' mod
  mods/lord/defaults/mod.conf
Labels: fix

#885 unblock in `default:`: `silver_sand`, blueberry & two "mese post lights"
  mods/lord/_overwrites/MTG/default/init.lua
Labels: enhancement, new block

#898 Closes #894. Remove 'default:junglesapling', use 'lottplants:mirksapling' instead
  mods/lord/_overwrites/MTG/default/init.lua
  mods/lord/legacy/init.lua
Labels: fix

#899 Closes #894. Remove junglesapling and jungleleaves
  mods/lord/_overwrites/MTG/default/init.lua
  mods/lord/legacy/init.lua
Labels: fix

#900 Closes #894. Fix an error with default:jungleleaves
  mods/lord/_overwrites/MTG/default/init.lua
  mods/lord/_overwrites/MTG/default/mapgen.lua
Labels: fix

#897 #755 add reward chest for quests
  mods/lord/quest/modpack.conf
  mods/lord/quest/quest_node/init.lua
  mods/lord/quest/quest_node/locale/quest_node.ru.tr
  mods/lord/quest/quest_node/locale/template.txt
  mods/lord/quest/quest_node/mod.conf
  mods/lord/quest/quest_node/src/reward_chest.lua
  mods/lord/quest/quest_node/src/reward_chest/node.lua
  mods/lord/quest/quest_node/src/reward_chest/node/Form.lua
  util/mt-ide-helper/classes/InvRef.lua
  util/mt-ide-helper/classes/ObjectRef/Entity.lua
  util/mt-ide-helper/minetest_types.lua
Labels: feature

#901 Hotfix: add LBM's and aliases to replace junglesapling and jungleleaf
  mods/lord/_overwrites/MTG/default/init.lua
  mods/lord/legacy/init.lua
Labels: hotfix
