Repository lord-server/lord, pull requests merged in 2022-04, with the labels that each got.

#579 559_fix-pearl-transparency
  mods/_lott/lottores/init.lua
  mods/_lott/lottores/textures/lottores_pearl_block.png
Labels: fix

#577 New crystal textures
  mods/_lott/lottores/textures/lottores_bluegem.png
  mods/_lott/lottores/textures/lottores_redgem.png
  mods/_lott/lottores/textures/lottores_whitegem.png
  mods/_lott/lottother/textures/lottother_purplegem.png
  mods/lord/_overwrites/MTG/default/textures/default_diamond.png
  mods/lord/_overwrites/MTG/default/textures/default_mese_crystal.png
Labels: graphics

#570 Ores item textures
  mods/_lott/lottores/textures/lottores_lead_lump.png
  mods/_lott/lottores/textures/lottores_limestone_lump.png
  mods/_lott/lottores/textures/lottores_mithril_lump.png
  mods/_lott/lottores/textures/lottores_rough_rock_lump.png
  mods/_lott/lottores/textures/lottores_silver_lump.png
  mods/_lott/lottores/textures/lottores_tin_lump.png
  mods/_lott/lottother/textures/lottother_ringsilver_lump.png
  mods/lord/_overwrites/MTG/default/textures/default_copper_lump.png
  mods/lord/_overwrites/MTG/default/textures/default_gold_lump.png
  mods/lord/_overwrites/MTG/default/textures/default_iron_lump.png
Labels: graphics

#580 Update `MTG/sethome`. Closes #573.
  mods/_minetest_game/sethome/README.txt
  mods/_minetest_game/sethome/depends.txt
  mods/_minetest_game/sethome/init.lua
  mods/_minetest_game/sethome/license.txt
  mods/_minetest_game/sethome/locale/en.txt
  mods/_minetest_game/sethome/locale/ru.txt
  mods/_minetest_game/sethome/locale/sethome.de.tr
  mods/_minetest_game/sethome/locale/sethome.es.tr
  mods/_minetest_game/sethome/locale/sethome.fr.tr
  mods/_minetest_game/sethome/locale/sethome.id.tr
  mods/_minetest_game/sethome/locale/sethome.it.tr
  mods/_minetest_game/sethome/locale/sethome.jbo.tr
  mods/_minetest_game/sethome/locale/sethome.ms.tr
  mods/_minetest_game/sethome/locale/sethome.pt_BR.tr
  mods/_minetest_game/sethome/locale/sethome.ru.tr
  mods/_minetest_game/sethome/locale/sethome.se.tr
  mods/_minetest_game/sethome/locale/sethome.sk.tr
  mods/_minetest_game/sethome/locale/sethome.zh_CN.tr
  mods/_minetest_game/sethome/locale/sethome.zh_TW.tr
  mods/_minetest_game/sethome/locale/template.txt
  mods/_minetest_game/sethome/mod.conf
  mods/lord/_overwrites/MTG/sethome/init.lua
  mods/lord/_overwrites/MTG/sethome/mod.conf
Labels: mod, external, update, MTG

#581 Fix crosshair.png symmetry. Add object_crosshair.png
  mods/_various/hud_modpack/hudbars/textures/crosshair.png
  mods/_various/hud_modpack/hudbars/textures/object_crosshair.png
Labels: fix

#583 Fix wooden axe
  mods/lord/tools/axes.lua
Labels: fix

#584 #437 Add Diamond Block stairs & slabs
  mods/lord/_overwrites/MTG/stairs/init.lua
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.de.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.es.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.fr.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.id.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.it.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.jbo.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.ms.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.pt_BR.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.ru.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.se.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.sk.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.zh_CN.tr
  mods/lord/_overwrites/MTG/stairs/locale/lord_overwrites_mtg_stairs.zh_TW.tr
  mods/lord/_overwrites/MTG/stairs/locale/template.txt
Labels: fix, new block

#585 Fix new player hunger
  mods/_various/hud_modpack/hbhunger/init.lua
Labels: fix, hud, characteristics

#591 New coal and charcoal textures
  mods/lord/_overwrites/MTG/default/textures/default_coal_lump.png
  mods/lord/lord_default/textures/charcoal_lump.png
Labels: graphics
