Repository lord-server/lord, pull requests merged in 2022-01, with the labels that each got.

#511 Added translation of inner & outer stairs
  mods/_lott/lottblocks/decoration.lua
  mods/_lott/lottblocks/init.lua
  mods/_lott/lottblocks/locale/en.txt
  mods/_lott/lottblocks/locale/ru.txt
  mods/_lott/lottmapgen/locale/en.txt
  mods/_lott/lottmapgen/locale/ru.txt
  mods/_lott/lottmapgen/nodes.lua
  mods/_lott/lottores/init.lua
  mods/_lott/lottores/locale/en.txt
  mods/_lott/lottores/locale/ru.txt
  mods/_lott/lottplants/locale/en.txt
  mods/_lott/lottplants/locale/ru.txt
  mods/_lott/lottplants/nodes.lua
  mods/_various/castle/init.lua
  mods/_various/castle/locale/en.txt
  mods/_various/castle/locale/ru.txt
  mods/_various/castle/town_item.lua
  mods/lord/lord_homedecor/building_blocks.lua
  mods/lord/lord_homedecor/locale/lord_homedecor.en.tr
  mods/lord/lord_homedecor/locale/lord_homedecor.ru.tr
  mods/lord/lord_homedecor/locale/template.txt
Labels: localization, fix, low-priority

#516 Update mods: MTG/screwdriver
  mods/_minetest_game/screwdriver/README.txt
  mods/_minetest_game/screwdriver/depends.txt
  mods/_minetest_game/screwdriver/init.lua
  mods/_minetest_game/screwdriver/license.txt
  mods/_minetest_game/screwdriver/locale/en.txt
  mods/_minetest_game/screwdriver/locale/ru.txt
  mods/_minetest_game/screwdriver/locale/screwdriver.de.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.es.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.fr.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.id.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.it.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.jbo.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.ms.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.pt_BR.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.ru.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.se.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.sk.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.zh_CN.tr
  mods/_minetest_game/screwdriver/locale/screwdriver.zh_TW.tr
  mods/_minetest_game/screwdriver/locale/template.txt
  mods/_minetest_game/screwdriver/mod.conf
  mods/_minetest_game/screwdriver/readme.txt
  mods/_minetest_game/screwdriver/textures/screwdriver.png
  mods/_minetest_game/screwdriver/textures/screwdriver_galvorn.png
  mods/lord/_overwrites/MTG/screwdriver/init.lua
  mods/lord/_overwrites/MTG/screwdriver/mod.conf
  mods/lord/_overwrites/MTG/screwdriver/readme.md
  mods/lord/_overwrites/readme.md
  mods/lord/lord_screwdriver/init.lua
  mods/lord/lord_screwdriver/locale/lord_screwdriver.ru.tr
  mods/lord/lord_screwdriver/locale/template.txt
  mods/lord/lord_screwdriver/mod.conf
  mods/lord/lord_screwdriver/textures/screwdriver.png
  mods/lord/lord_screwdriver/textures/screwdriver_galvorn.png
  mods/lord/readme.md
Labels: mod, external, update, MTG

#412 WIP: Prepare code to 5.4.1 server
  mods/_various/mobs/api.lua
  mods/lord/throwing/init.lua
Labels: fix

#363 Build dependency graph
  development.md
  util/build_graph.py
Labels: enhancement, waiting on review

#528 Update mods: MTG/player_api
  mods/_minetest_game/player_api/README.txt
  mods/_minetest_game/player_api/api.lua
  mods/_minetest_game/player_api/init.lua
  mods/_minetest_game/player_api/license.txt
  mods/_minetest_game/player_api/models/character.b3d
  mods/_minetest_game/player_api/models/character.blend
Labels: mod, external, update, MTG
