Repository lord-server/lord, pull requests merged in 2022-09, with the labels that each got.

#718 Moved lottpotion from _lott/ to lord/
  mods/lord/lottpotion/arrows.lua
  mods/lord/lottpotion/brewing.lua
  mods/lord/lottpotion/cauldron.lua
  mods/lord/lottpotion/init.lua
  mods/lord/lottpotion/license.txt
  mods/lord/lottpotion/locale/en.txt
  mods/lord/lottpotion/locale/ru.txt
  mods/lord/lottpotion/mod.conf
  mods/lord/lottpotion/potionbrewing.lua
  mods/lord/lottpotion/textures/gui_brewerbg.png
  mods/lord/lottpotion/textures/lottpotion_ale.png
  mods/lord/lottpotion/textures/lottpotion_arrow.png
  mods/lord/lottpotion/textures/lottpotion_athelasbrew.png
  mods/lord/lottpotion/textures/lottpotion_beer.png
  mods/lord/lottpotion/textures/lottpotion_bottle.png
  mods/lord/lottpotion/textures/lottpotion_bubble.png
  mods/lord/lottpotion/textures/lottpotion_bubble_off.png
  mods/lord/lottpotion/textures/lottpotion_cauldron_side.png
  mods/lord/lottpotion/textures/lottpotion_cauldron_top.png
  mods/lord/lottpotion/textures/lottpotion_cider.png
  mods/lord/lottpotion/textures/lottpotion_corruption1.png
  mods/lord/lottpotion/textures/lottpotion_corruption2.png
  mods/lord/lottpotion/textures/lottpotion_corruption3.png
  mods/lord/lottpotion/textures/lottpotion_entdraught.png
  mods/lord/lottpotion/textures/lottpotion_glass_water.png
  mods/lord/lottpotion/textures/lottpotion_grey.png
  mods/lord/lottpotion/textures/lottpotion_limpe.png
  mods/lord/lottpotion/textures/lottpotion_mead.png
  mods/lord/lottpotion/textures/lottpotion_miruvor.png
  mods/lord/lottpotion/textures/lottpotion_orcdraught.png
  mods/lord/lottpotion/textures/lottpotion_potion_brewer.png
  mods/lord/lottpotion/textures/lottpotion_potion_brewer_active.png
  mods/lord/lottpotion/textures/lottpotion_power1.png
  mods/lord/lottpotion/textures/lottpotion_power2.png
  mods/lord/lottpotion/textures/lottpotion_power3.png
  mods/lord/lottpotion/textures/lottpotion_shatter.png
  mods/lord/lottpotion/textures/lottpotion_spiderpoison.png
  mods/lord/lottpotion/textures/lottpotion_water.png
  mods/lord/lottpotion/textures/lottpotion_water_bonedust.png
  mods/lord/lottpotion/textures/lottpotion_water_geodes.png
  mods/lord/lottpotion/textures/lottpotion_water_glass.png
  mods/lord/lottpotion/textures/lottpotion_water_mese.png
  mods/lord/lottpotion/textures/lottpotion_water_mordor.png
  mods/lord/lottpotion/textures/lottpotion_water_obsidian.png
  mods/lord/lottpotion/textures/lottpotion_water_seregon.png
  mods/lord/lottpotion/textures/lottpotion_wine.png
  mods/lord/lottpotion/textures/lottthrowing_arrow_magical.png
  mods/lord/lottpotion/textures/lottthrowing_arrow_magical_2.png
  mods/lord/lottpotion/textures/lottthrowing_arrow_magical_back.png
  mods/lord/lottpotion/textures/lottthrowing_arrow_magical_front.png
Labels: refactoring

#699 Add core_callbacks
  mods/lord/lordlib/core_functions.lua
  mods/lord/lordlib/init.lua
Labels: lord

#758 Исправление автоматического срубания дерева
  mods/_lott/lottplants/nodes.lua
  mods/lord/_overwrites/MTG/default/init.lua
Labels: fix

#764 Добавление плит и ступенек из зелёного мрамора
  mods/lord/lord_blocks/init.lua
  mods/lord/lord_blocks/locale/lord_blocks.en.tr
  mods/lord/lord_blocks/locale/lord_blocks.ru.tr
  mods/lord/lord_blocks/locale/template.txt
Labels: new block

#761 Повторное использование бутылок из-под зелий
  mods/lord/lottpotion/init.lua
Labels: enhancement

#766 Покрытие корой второй стороны полублоков из стволов дерева
  mods/_lott/lottplants/nodes.lua
Labels: enhancement, graphics

#769 Добавление овцы
  mods/_lott/lottmobs/animals.lua
  mods/_lott/lottmobs/license.txt
  mods/_lott/lottmobs/textures/mobs_sheep_base.png
  mods/_lott/lottmobs/textures/mobs_sheep_wool.png
Labels: mobs | entities

#771 Lottblocks update
  mods/_lott/lottblocks/chests.lua
  mods/_lott/lottblocks/decoration.lua
  mods/_lott/lottblocks/lamps.lua
  mods/_lott/lottblocks/license.txt
  mods/_lott/lottblocks/locale/en.txt
  mods/_lott/lottblocks/locale/ru.txt
  mods/_lott/lottblocks/music.lua
  mods/_lott/lottblocks/palantiri.lua
  mods/_lott/lottblocks/sounds/gong.ogg
  mods/_lott/lottblocks/textures/gui_dwarfbg.png
  mods/_lott/lottblocks/textures/lottblocks_dwarf_chest_bottom.png
  mods/_lott/lottblocks/textures/lottblocks_dwarf_chest_front.png
  mods/_lott/lottblocks/textures/lottblocks_dwarf_chest_side.png
  mods/_lott/lottblocks/textures/lottblocks_dwarf_chest_top.png
  mods/_lott/lottblocks/textures/lottblocks_mithril_stonelamp.png
  mods/_lott/lottblocks/wooden_stuff.lua
Labels: update, new block, LOTT

#776 Lottblocks i18n -> minetest.get_translator()
  mods/_lott/lottblocks/chests.lua
  mods/_lott/lottblocks/decoration.lua
  mods/_lott/lottblocks/guides.lua
  mods/_lott/lottblocks/init.lua
  mods/_lott/lottblocks/lamps.lua
  mods/_lott/lottblocks/locale/lottblocks.en.tr
  mods/_lott/lottblocks/locale/lottblocks.ru.tr
  mods/_lott/lottblocks/misc.lua
  mods/_lott/lottblocks/music.lua
  mods/_lott/lottblocks/palantiri.lua
  mods/_lott/lottblocks/wooden_stuff.lua
Labels: refactoring, localization

#781 add Shire Tapestry. Closes #358
  mods/_lott/lottother/flags.lua
  mods/_lott/lottother/locale/en.txt
  mods/_lott/lottother/locale/ru.txt
  mods/_lott/lottother/textures/lottother_banner_shire.png
  mods/_lott/lottother/textures/lottother_banner_top_shire.png
Labels: graphics, feature

#787 Implemented races.race_stuff_opener
  mods/_lott/lottblocks/chests.lua
  mods/_lott/lottblocks/locale/lottblocks.en.tr
  mods/_lott/lottblocks/locale/lottblocks.ru.tr
  mods/lord/lord_classes/init.lua
  mods/lord/lord_classes/locale/lord_classes.en.tr
Labels: enhancement, lord, LOTT

#791 Исправление дна расовых сундуков
  mods/_lott/lottblocks/chests.lua
  mods/_lott/lottblocks/textures/lottblocks_angmar_chest_bottom.png
  mods/_lott/lottblocks/textures/lottblocks_hobbit_chest_bottom.png
Labels: graphics

#792 Add side textures of apropriate color for every hatch
  mods/_lott/lottblocks/textures/lottblocks_hatch_alder_side.png
  mods/_lott/lottblocks/textures/lottblocks_hatch_birch_side.png
  mods/_lott/lottblocks/textures/lottblocks_hatch_junglewood_side.png
  mods/_lott/lottblocks/textures/lottblocks_hatch_lebethron_side.png
  mods/_lott/lottblocks/textures/lottblocks_hatch_mallorn_side.png
  mods/_lott/lottblocks/textures/lottblocks_hatch_pine_side.png
  mods/_lott/lottblocks/wooden_stuff.lua
Labels: graphics, LOTT

#790 Небольшое изменение `defaults:`
  mods/lord/defaults/init.lua
Labels: fix

#789 Расовые двери
  mods/lord/lord_doors/init.lua
  mods/lord/lord_doors/locale/lord_doors.en.tr
  mods/lord/lord_doors/locale/lord_doors.ru.tr
  mods/lord/lord_doors/locale/template.txt
  mods/lord/lord_doors/race_doors.lua
  mods/lord/lord_doors/textures/lord_doors_dwarf.png
  mods/lord/lord_doors/textures/lord_doors_elven.png
  mods/lord/lord_doors/textures/lord_doors_hobbit.png
  mods/lord/lord_doors/textures/lord_doors_human.png
  mods/lord/lord_doors/textures/lord_doors_item_dwarf.png
  mods/lord/lord_doors/textures/lord_doors_item_elven.png
  mods/lord/lord_doors/textures/lord_doors_item_hobbit.png
  mods/lord/lord_doors/textures/lord_doors_item_human.png
  mods/lord/lord_doors/textures/lord_doors_item_orc.png
  mods/lord/lord_doors/textures/lord_doors_orc.png
Labels: lord, needs testing, new block, implementation, LOTT
