Repository lord-server/lord, pull requests merged in 2023-06, with the labels that each got.

#1002 Closes #995. Add mod lord_bricks, add 2 types of bricks (and their crafts)
  mods/lord/clay_types/init.lua
  mods/lord/clay_types/locale/clay_types.ru.tr
  mods/lord/clay_types/mod.conf
  mods/lord/clay_types/textures/clay_types_chamotte_block_dried.png
  mods/lord/clay_types/textures/clay_types_chamotte_block_raw.png
  mods/lord/clay_types/textures/clay_types_chamotte_lump.png
  mods/lord/clay_types/textures/clay_types_mordor_clay_block_dried.png
  mods/lord/clay_types/textures/clay_types_mordor_clay_block_raw.png
  mods/lord/clay_types/textures/clay_types_mordor_clay_lump.png
  mods/lord/grinder/src/grinder/definition/recipes.lua
  mods/lord/lord_bricks/crafts.lua
  mods/lord/lord_bricks/init.lua
  mods/lord/lord_bricks/locale/lord_bricks.ru.tr
  mods/lord/lord_bricks/mod.conf
  mods/lord/lord_bricks/nodes.lua
  mods/lord/lord_bricks/textures/lord_bricks_chamotte_block.png
  mods/lord/lord_bricks/textures/lord_bricks_chamotte_brick.png
  mods/lord/lord_bricks/textures/lord_bricks_chamotte_brick_dried.png
  mods/lord/lord_bricks/textures/lord_bricks_chamotte_brick_raw.png
  mods/lord/lord_bricks/textures/lord_bricks_chamotte_masonry.png
  mods/lord/lord_bricks/textures/lord_bricks_chamotte_masonry_large.png
  mods/lord/lord_bricks/textures/lord_bricks_clay_brick_raw.png
  mods/lord/lord_bricks/textures/lord_bricks_mordor_clay_block.png
  mods/lord/lord_bricks/textures/lord_bricks_mordor_clay_brick.png
  mods/lord/lord_bricks/textures/lord_bricks_mordor_clay_brick_dried.png
  mods/lord/lord_bricks/textures/lord_bricks_mordor_clay_brick_raw.png
  mods/lord/lord_bricks/textures/lord_bricks_mordor_clay_masonry.png
  mods/lord/lord_bricks/textures/lord_bricks_mordor_clay_masonry_large.png
Labels: new block, implementation

#1055 Closes #1052. Fix 'Raw Mordor Clay Block' grinder craft
  mods/lord/Blocks/grinder/src/grinder/definition/recipes.lua
Labels: fix

#1056 Change default brick texture
  mods/lord/_overwrites/MTG/default/textures/default_brick.png
Labels: graphics

#1061 Closes #1060. Add nil check
  mods/lord/lottarmor/armor.lua
Labels: hotfix

#1067 Forgoten fix from prod. Difficult to reproduce fatal. Was found & fixed on prod.
  mods/lord/Blocks/grinder/src/grinder/Processor.lua
  mods/lord/Blocks/grinder/src/grinder/Recipe.lua
Labels: fix, CRITICAL

#1074 Добавление проверки на пустой инвентарь при попытке разобрать центрифугу
  mods/lord/bees/init.lua
Labels: fix

#1075 Исправление ошибки #1010: Добавление дефолтного значения, если поле ввода пусто
  mods/lord/mountgen/init.lua
Labels: fix

#1076 Удаление вызова on_place в регистрации книги достижений (fix #1069)
  mods/lord/lottachievements/init.lua
Labels: fix

#1068 Исправление краша из-за формы сумок (fix 1066)
  mods/lord/Player/lord_inventory/src/inventory.lua
  mods/lord/Player/lord_inventory/src/inventory/bags_form.lua
Labels: fix, hotfix

#1065 Closes #1062. Fix translations. Add missing crafts
  mods/lord/Blocks/clay_types/locale/clay_types.ru.tr
  mods/lord/Blocks/lord_bricks/crafts.lua
  mods/lord/Blocks/lord_bricks/init.lua
  mods/lord/Blocks/lord_bricks/locale/lord_bricks.ru.tr
Labels: hotfix
