Repository lord-server/lord, pull requests merged in 2023-05, with the labels that each got.

#1030 Удаление хардкорных переводов в lottachievements (fix 1025)
  mods/_lott/lottachievements/init.lua
  mods/_lott/lottachievements/locale/ru.txt
  mods/_lott/lottachievements/triggers.lua
Labels: fix

#1032 Переход на встроенные переводы [lottachievements]
  mods/_lott/lottachievements/api.lua
  mods/_lott/lottachievements/chat_commands.lua
  mods/_lott/lottachievements/init.lua
  mods/_lott/lottachievements/intllib.lua
  mods/_lott/lottachievements/locale/lottachievements.en.tr
  mods/_lott/lottachievements/locale/lottachievements.ru.tr
  mods/_lott/lottachievements/locale/ru.txt
  mods/_lott/lottachievements/locale/template.txt
  mods/_lott/lottachievements/triggers.lua
Labels: localization

#1034 Исправление локализации реплики в достижениях
  mods/_lott/lottachievements/api.lua
  mods/_lott/lottachievements/locale/lottachievements.ru.tr
Labels: localization

#1036 Исправление целевой ноды достижения "Тормоз!"
  mods/_lott/lottachievements/init.lua
Labels: fix

#1037 Исправление названий текстур в иконках достижений
  mods/_lott/lottachievements/init.lua
Labels: fix

#1035 Новые текстуры колец
  mods/lord/lottother/textures/lottother_beast_ring.png
  mods/lord/lottother/textures/lottother_bluegem_am_ring.png
  mods/lord/lottother/textures/lottother_bluegem_ring.png
  mods/lord/lottother/textures/lottother_dwarf_ring.png
  mods/lord/lottother/textures/lottother_narya.png
  mods/lord/lottother/textures/lottother_nenya_inv.png
  mods/lord/lottother/textures/lottother_purplegem_am_ring.png
  mods/lord/lottother/textures/lottother_purplegem_mithril_ring.png
  mods/lord/lottother/textures/lottother_purplegem_ring.png
  mods/lord/lottother/textures/lottother_redgem_am_ring.png
  mods/lord/lottother/textures/lottother_redgem_ring.png
  mods/lord/lottother/textures/lottother_ring.png
  mods/lord/lottother/textures/lottother_vilya.png
  mods/lord/lottother/textures/lottother_whitegem_am_ring.png
  mods/lord/lottother/textures/lottother_whitegem_ring.png
Labels: graphics, LOTT

#1041 Новые текстуры книг
  mods/_lott/lottachievements/textures/lottachievements_achievement_book.png
  mods/lord/Tools/lord_books/textures/brewing_book.png
  mods/lord/Tools/lord_books/textures/cooking_book.png
  mods/lord/Tools/lord_books/textures/crafts_book.png
  mods/lord/Tools/lord_books/textures/forbidden_book.png
  mods/lord/Tools/lord_books/textures/master_book.png
  mods/lord/Tools/lord_books/textures/potion_book.png
  mods/lord/Tools/lord_books/textures/protection_book.png
  mods/lord/_overwrites/MTG/default/textures/default_book.png
  mods/lord/lord_mail/textures/mail_book_with_text.png
  mods/lord/lottblocks/guides.lua
  mods/lord/lottblocks/textures/lottblocks_palantir_guide.png
Labels: enhancement, graphics

#1042 Desert textures fix 2
  mods/lord/_overwrites/MTG/default/textures/default_desert_cobble.png
  mods/lord/_overwrites/MTG/default/textures/default_desert_stone_block.png
  mods/lord/_overwrites/MTG/default/textures/default_desert_stone_brick.png
Labels: graphics, fix

#1045 Closes #999. Add Mordor Brick, Orc Stone, change crafts and textures
  mods/_lott/lottmapgen/locale/lottmapgen.ru.tr
  mods/_lott/lottmapgen/nodes.lua
  mods/_lott/lottmapgen/textures/lottmapgen_mordor_cobble.png
  mods/_lott/lottmapgen/textures/lottmapgen_mordor_gravel.png
  mods/_lott/lottmapgen/textures/lottmapgen_mordor_sand.png
  mods/lord/grinder/src/grinder/definition/recipes.lua
  mods/lord/lottblocks/init.lua
  mods/lord/lottblocks/locale/lottblocks.ru.tr
  mods/lord/lottblocks/textures/lottblocks_mordor_stone_block.png
  mods/lord/lottblocks/textures/lottblocks_mordor_stone_brick.png
  mods/lord/lottblocks/textures/lottblocks_orc_block.png
  mods/lord/lottblocks/textures/lottblocks_orc_brick.png
  mods/lord/lottblocks/textures/lottblocks_orc_stone.png
Labels: graphics, fix, new block, implementation
