Repository lord-server/lord, pull requests merged in 2023-02, with the labels that each got.

#981 Closes #980. Fix fences connection. Add hardwood fences
  mods/lord/lord_homedecor/building_blocks.lua
  mods/lord/lord_homedecor/locale/lord_homedecor.ru.tr
  mods/lord/lord_homedecor/mod.conf
  mods/lord/lottblocks/locale/lottblocks.ru.tr
  mods/lord/lottblocks/textures/lottblocks_door_hardwood.png
  mods/lord/lottblocks/textures/lottblocks_door_hardwood_uv.png
  mods/lord/lottblocks/textures/lottblocks_fence_hardwood.png
  mods/lord/lottblocks/textures/lottblocks_hardwood.png
  mods/lord/lottblocks/textures/lottblocks_hardwood_ladder.png
  mods/lord/lottblocks/textures/lottblocks_hardwood_planks.png
  mods/lord/lottblocks/textures/lottblocks_hardwood_stick.png
  mods/lord/lottblocks/textures/lottblocks_hatch_hardwood.png
  mods/lord/lottblocks/textures/lottblocks_hatch_hardwood_open.png
  mods/lord/lottblocks/textures/lottblocks_hatch_hardwood_side.png
  mods/lord/lottblocks/wooden_stuff.lua
Labels: fix, new block

#982 Увелечение скорости зарядки и полета стрелы
  mods/lord/_experimental/lord_bows/mechanics_throwing.lua
Labels: lord

#983 Переход на встроенные переводы [lottpotion]
  mods/lord/Tools/lottpotion/arrows.lua
  mods/lord/Tools/lottpotion/brewing.lua
  mods/lord/Tools/lottpotion/cauldron.lua
  mods/lord/Tools/lottpotion/init.lua
  mods/lord/Tools/lottpotion/locale/en.txt
  mods/lord/Tools/lottpotion/locale/lottpotion.en.tr
  mods/lord/Tools/lottpotion/locale/lottpotion.ru.tr
  mods/lord/Tools/lottpotion/locale/ru.txt
  mods/lord/Tools/lottpotion/locale/template.txt
  mods/lord/Tools/lottpotion/potionbrewing.lua
Labels: localization

#991 Переход на встроенные переводы [mypos]
  mods/lord/mypos/init.lua
  mods/lord/mypos/locale/mypos.en.tr
  mods/lord/mypos/locale/mypos.ru.tr
  mods/lord/mypos/locale/ru.txt
  mods/lord/mypos/locale/template.txt
Labels: localization

#990 Переход на встроенные переводы [mail_list]
  mods/lord/mail_list/init.lua
  mods/lord/mail_list/locale/mail_list.en.tr
  mods/lord/mail_list/locale/mail_list.ru.tr
  mods/lord/mail_list/locale/ru.txt
  mods/lord/mail_list/locale/template.txt
Labels: localization

#987 Переход на встроенные переводы [lottores]
  mods/lord/lottores/init.lua
  mods/lord/lottores/locale/en.txt
  mods/lord/lottores/locale/lottores.en.tr
  mods/lord/lottores/locale/lottores.ru.tr
  mods/lord/lottores/locale/ru.txt
  mods/lord/lottores/locale/template.txt
Labels: localization

#986 Переход на встроенные переводы [lottfarming]
  mods/lord/lottfarming/athelas.lua
  mods/lord/lottfarming/barley.lua
  mods/lord/lottfarming/berries.lua
  mods/lord/lottfarming/blue.lua
  mods/lord/lottfarming/brown.lua
  mods/lord/lottfarming/cabbage.lua
  mods/lord/lottfarming/carrots.lua
  mods/lord/lottfarming/corn.lua
  mods/lord/lottfarming/crafting.lua
  mods/lord/lottfarming/green.lua
  mods/lord/lottfarming/locale/en.txt
  mods/lord/lottfarming/locale/lottfarming.en.tr
  mods/lord/lottfarming/locale/lottfarming.ru.tr
  mods/lord/lottfarming/locale/ru.txt
  mods/lord/lottfarming/locale/template.txt
  mods/lord/lottfarming/melon.lua
  mods/lord/lottfarming/orc_food.lua
  mods/lord/lottfarming/other.lua
  mods/lord/lottfarming/pipeweed.lua
  mods/lord/lottfarming/potato.lua
  mods/lord/lottfarming/red.lua
  mods/lord/lottfarming/tomatoes.lua
  mods/lord/lottfarming/turnips.lua
Labels: localization

#992 Исправление template и отсутствующих букв [lottores]
  mods/lord/lottores/locale/lottores.en.tr
  mods/lord/lottores/locale/lottores.ru.tr
  mods/lord/lottores/locale/template.txt
Labels: localization

#993 Исправление template, разбиение по файлам [lottpotion]
  mods/lord/Tools/lottpotion/locale/lottpotion.en.tr
  mods/lord/Tools/lottpotion/locale/lottpotion.ru.tr
  mods/lord/Tools/lottpotion/locale/template.txt
Labels: localization

#994 добавление template [bags]
  mods/lord/Tools/bags/locale/template.txt
Labels: localization

#985 Переход на встроенные переводы [lottclother]
  mods/lord/lottclothes/brandybuck.lua
  mods/lord/lottclothes/chetwood.lua
  mods/lord/lottclothes/cloaks.lua
  mods/lord/lottclothes/elven.lua
  mods/lord/lottclothes/ettenmoor.lua
  mods/lord/lottclothes/fabrics.lua
  mods/lord/lottclothes/hobbit.lua
  mods/lord/lottclothes/locale/en.txt
  mods/lord/lottclothes/locale/lottclothes.en.tr
  mods/lord/lottclothes/locale/lottclothes.ru.tr
  mods/lord/lottclothes/locale/ru.txt
  mods/lord/lottclothes/locale/template.txt
  mods/lord/lottclothes/midgewater.lua
  mods/lord/lottclothes/wizard.lua
Labels: localization

#988 Переход на встроенные переводы [lottother]
  mods/lord/lottother/flags.lua
  mods/lord/lottother/init.lua
  mods/lord/lottother/locale/en.txt
  mods/lord/lottother/locale/lottother.en.tr
  mods/lord/lottother/locale/lottother.ru.tr
  mods/lord/lottother/locale/ru.txt
  mods/lord/lottother/locale/template.txt
  mods/lord/lottother/ms.lua
  mods/lord/lottother/rings.lua
Labels: localization

#989 Переход на встроенные переводы [lottmobs]
  mods/lord/lottmobs/animals.lua
  mods/lord/lottmobs/boar.lua
  mods/lord/lottmobs/craftitems.lua
  mods/lord/lottmobs/fishes.lua
  mods/lord/lottmobs/horse.lua
  mods/lord/lottmobs/init.lua
  mods/lord/lottmobs/locale/en.txt
  mods/lord/lottmobs/locale/lottmobs.en.tr
  mods/lord/lottmobs/locale/lottmobs.ru.tr
  mods/lord/lottmobs/locale/ru.txt
  mods/lord/lottmobs/locale/template.txt
  mods/lord/lottmobs/trader.lua
  mods/lord/lottmobs/trader_goods.lua
  mods/lord/lottmobs/warg.lua
Labels: localization

#984 Переход на встроенные переводы [bones]
  mods/lord/bones/init.lua
  mods/lord/bones/items.lua
  mods/lord/bones/locale/bones.en.tr
  mods/lord/bones/locale/bones.ru.tr
  mods/lord/bones/locale/en.txt
  mods/lord/bones/locale/ru.txt
  mods/lord/bones/locale/template.txt
  mods/lord/bones/skeleton.lua
Labels: localization
