Repository lord-server/lord, pull requests merged in 2024-08, with the labels that each got.

#1607 Fix overpowered Bone Scythe; make it reach farther
  mods/lord/Player/bones/items.lua
Labels: hotfix

#1612 Add ObjectState class. Closes #1515
  mods/lord/Core/base_classes/src/base_classes.lua
  mods/lord/Core/base_classes/src/base_classes/ObjectState.lua
  mods/lord/Core/base_classes/src/base_classes/ObjectState/Storage.lua
Labels: feature, implementation

#1617 Fix painting brushes crafting
  mods/lord/Blocks/lottfarming/init.lua
  mods/lord/Blocks/lottfarming/locale/lottfarming.en.tr
  mods/lord/Blocks/lottfarming/locale/lottfarming.ru.tr
  mods/lord/Blocks/lottfarming/locale/template.txt
  mods/lord/Blocks/lottfarming/mod.conf
  mods/lord/Blocks/lottfarming/oil.lua
  mods/lord/Blocks/lottfarming/textures/lottfarming_vegetable_oil.png
  mods/lord/_overwrites/various/painting/init.lua
  mods/lord/_overwrites/various/painting/mod.conf
Labels: mod, LOTT
