Repository lord-server/lord, pull requests merged in 2025-02, with the labels that each got.

#1989 Fix #1938: Projectiles now always start a timer.
  mods/lord/Core/projectiles/src/projectiles/entity.lua
Labels: hotfix

#2016 Pancake in furnance
  mods/lord/Blocks/lottfarming/locale/lottfarming.ru.tr
  mods/lord/Blocks/lottfarming/other.lua
  mods/lord/Blocks/lottfarming/textures/lottfarming_dough_with_egg.png
  mods/lord/Tools/lord_food/init.lua
  mods/lord/Tools/lord_food/locale/lord_food.ru.tr
  mods/lord/Tools/lord_food/textures/lord_food_pancakes.png
  mods/lord/Tools/lord_food/textures/lord_food_pancakes_with_honey.png
Labels: idea

#2019 Правка вывода сообщений в чат
  mods/lord/Game/server_message/init.lua
Labels: A.I.

#2033 Locale some products from Plum and Hardwood. Related to #2003
  mods/lord/Blocks/lord_planks/locale/lord_planks.ru.tr
Labels: localization

#2030 Add glow to fire- and magic balls
  mods/lord/Tools/lord_projectiles/src/lord_projectiles/config.lua
Labels: graphics, mobs | entities
