Repository lord-server/lord, pull requests merged in 2025-01, with the labels that each got.

#1926 Fix palantire texture
  mods/lord/Blocks/lottblocks/textures/lottblocks_palantir_item.png
Labels: graphics, fix

#1940 Update meat textures
  mods/lord/Entities/lottmobs/textures/lottmobs_chicken_cooked.png
  mods/lord/Entities/lottmobs/textures/lottmobs_chicken_raw.png
  mods/lord/Entities/lottmobs/textures/lottmobs_egg.png
  mods/lord/Entities/lottmobs/textures/lottmobs_horsemeat_cooked.png
  mods/lord/Entities/lottmobs/textures/lottmobs_horsemeat_raw.png
  mods/lord/Entities/lottmobs/textures/lottmobs_meat.png
  mods/lord/Entities/lottmobs/textures/lottmobs_meat_raw.png
  mods/lord/Entities/lottmobs/textures/lottmobs_rabbit_cooked.png
  mods/lord/Entities/lottmobs/textures/lottmobs_rabbit_raw.png
  mods/lord/Entities/lottmobs/textures/lottmobs_rotten_meat.png
  mods/lord/Entities/lottmobs/textures/mobs_pork_cooked.png
  mods/lord/Entities/lottmobs/textures/mobs_pork_raw.png
Labels: graphics

#1941 Update bags textures
  mods/lord/Player/lord_inventory/textures/lord_inventory_bags_button.png
  mods/lord/Tools/bags/textures/bags_large.png
  mods/lord/Tools/bags/textures/bags_medium.png
  mods/lord/Tools/bags/textures/bags_small.png
Labels: graphics

#1944 Update screwdriver textures
  mods/lord/Tools/lord_screwdriver/textures/screwdriver.png
  mods/lord/Tools/lord_screwdriver/textures/screwdriver_galvorn.png
Labels: graphics

#1943 Update bones textures
  mods/lord/Player/bones/textures/bones_bone.png
  mods/lord/Player/bones/textures/bones_bonedust.png
  mods/lord/Player/bones/textures/bones_scythe.png
Labels: graphics

#1973 Fix #1945: apply rotation before applying speed
  mods/lord/Core/archery/src/archery/processor/processing_api.lua
  mods/lord/Core/projectiles/src/projectiles/api.lua
  mods/lord/Core/projectiles/src/projectiles/entity.lua
Labels: fix

#1974 Fix #1897: set use_texture_alpha to false
  mods/lord/Core/projectiles/src/projectiles/entity.lua
Labels: fix
